spring:
  datasource:
#    url: jdbc:postgresql://postgres:5432/postgres
#    username: postgres
#    password: pass
     url: jdbc:postgresql://shopdb.cnjzhg51nfls.us-east-1.rds.amazonaws.com:5432/postgres
     username: postgres
     password: st0uti6idilt(650
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus